"""추가 10단계. 예상값과 버튼 실행 증거를 분리한다."""
def extend_more(steps, lesson):
    def make(id,title,group,situation,definition,example,before,after,changes,expected,why,caution,compare=None):
        s=lesson(id,title,group,situation,definition,example,before,after,changes,expected,why,caution,compare)
        s.update(extensionView=True,codeSource="scripts/extension_actions.py (핵심 구조 발췌)",
            watch=[expected,"포인트·HTTP 풀 공통 그래프 대신 아래 이 단계 전용 실측 증거를 읽는다."],
            terms=[["정의",definition],["이번 데이터",situation]],
            prompts=[["예상 상태",expected+" 왜 그렇게 예상했나요?"],["실패 경계","어디까지 저장되고 어디부터 미완료일까요?"],["복구","같은 작업을 다시 하면 무엇이 중복될까요?"]],
            reading=[["무엇을 세나",expected],["변경의 의미",why],["한계",caution]])
        return s
    batch_wait=make("batch_wait","배치 · 원본은 있는데 왜 수신 데이터는 없을까?","07 · 배치 — 시간 분리",
        "포인트 지급과 분리한 리뷰 복제 예제다. 원본 리뷰 3개를 저장하지만 파일 내보내기는 아직 실행하지 않는다.",
        "배치는 여러 데이터를 모아 정해진 시점에 한꺼번에 처리하는 방식이다. 원본 커밋과 수신 반영 사이에 시간차가 있다.",
        "매 주문마다 택배사에 연락하지 않고 오후 5시에 발송 목록을 모아 보내는 것과 같다.",
        "원본 저장 → 즉시 외부 API 호출 → 응답 대기",
        "원본 저장 → 사용자 응답\n[배치 시점] 원본 조회 → 파일 생성 → 수신 반영",
        "버튼은 새 원본 3건만 DB에 저장한다. 다음 버튼을 누르는 시점을 예약 배치 실행 시점으로 대신한다. 실제 cron을 기다리게 하지는 않는다.",
        "원본 3 / 수신 0 / 미반영 3. 아직 전송하지 않았으므로 장애가 아니라 의도한 지연이다.",
        "비동기는 ‘즉시 끝남’이 아니다. 수신자가 언제까지 데이터를 필요로 하는지가 배치 주기의 기준이다.",
        "정시 스케줄러·SFTP 서버·시간대 협상은 구현하지 않는다. 실제 JSONL 파일과 DB 수신 처리를 실험한다.")
    partial=make("batch_partial","문제 · 파일은 3건인데 한 건만 반영됐다","07 · 배치 — 부분 실패",
        "같은 리뷰 3개를 실제 JSONL 파일로 만든다. 수신자가 첫 행을 커밋한 직후 처리를 의도적으로 중단한다.",
        "부분 실패는 전체 작업 일부만 성공한 상태다. 파일을 받았다는 사실과 모든 행을 반영했다는 사실은 다르다.",
        "3장짜리 주문서를 받았지만 첫 장만 입력한 뒤 업무가 멈춘 상황이다.",
        "for row in file:\n    insert(row)  # 각 행 커밋\n    # 1행 뒤 장애: 앞 행은 이미 저장됨",
        "records = read_jsonl(file)\nverify_sha256_and_count(records)\n# 다음 단계: 같은 파일을 재처리하되 업무 ID로 중복 방지",
        "임시 .part 파일을 완성한 뒤 .jsonl로 이름을 바꾼다. manifest에 건수와 SHA-256을 기록한다. 전송 완료 검증 후 첫 행까지만 수신 DB에 커밋한다.",
        "파일 3건 / 이번 신규 반영 1 / 수신 1 / 미반영 2. 파일 경로와 해시도 실측으로 표시한다.",
        "파일 검증은 손상·불완전 파일을 막지만, 이후 행별 업무 처리의 원자성까지 주지는 않는다.",
        "SHA-256은 이 예제에서 내용 무결성 비교용이다. 신뢰할 수 없는 발신자의 진위나 보안을 보장하는 서명은 아니다.","batch_wait")
    batch=make("batch_recover","해결 · 같은 파일을 다시 넣어도 세 건만 남기기","07 · 배치 — 재처리",
        "이전 파일을 다시 읽는다. 원본에서 새로 추출하지 않으므로 동일한 입력을 재처리한다.",
        "재처리 가능한 배치는 입력 파일과 처리 키를 보존하고, 이미 반영한 행의 효과를 중복하지 않게 설계한다.",
        "주문서 세 장을 다시 확인하면서 이미 입력한 주문 번호는 건너뛴다.",
        "INSERT INTO batch_received(id, content) VALUES (?, ?);\n-- 이미 반영한 첫 행과 충돌",
        "INSERT INTO batch_received(id, content) VALUES (?, ?)\nON CONFLICT(id) DO NOTHING;",
        "같은 파일의 해시·건수·세션 범위를 먼저 검증하고 3행을 다시 처리한다. 첫 행은 건너뛰고 나머지 2행을 반영한다. 파일과 결과는 runs에 남는다.",
        "이번 신규 반영 2 / 수신 총 3 / 미반영 0. 중복 행은 늘지 않는다.",
        "무조건 처음부터 재실행하는 것이 아니라, 반복해도 안전한 반영 규칙을 만들었기 때문에 복구할 수 있다.",
        "내용 변경을 허용하는 업무라면 같은 ID의 최신 버전·덮어쓰기 규칙도 필요하다. 빈 파일과 파일 미도착, 스케줄 중복 실행·경보도 구분해야 한다.","batch_partial")
    lag=make("cdc_lag","CDC · DB가 바뀌었는데 대상에는 왜 없을까?","08 · CDC — 로그 읽기",
        "전용 cdc_source를 INSERT·UPDATE·DELETE하고 별도 INSERT는 ROLLBACK한다. cdc_target에는 아직 전달하지 않는다.",
        "로그 기반 CDC는 DB의 변경 로그를 해석해 커밋된 행 변경을 다른 시스템에 전달하는 방식이다. 이 실습은 PostgreSQL WAL과 test_decoding을 사용한다.",
        "현재 장부 한 장을 복사하는 배치와 달리, 장부의 ‘추가·수정·삭제 기록’을 읽는다. 현재 한 행만 있어도 변경 기록은 여러 개일 수 있다.",
        "UPDATE cdc_source SET status='SHIPPED' WHERE id=?;\n// 대상 반영 코드가 없으면 대상 상태는 그대로",
        "SELECT * FROM pg_create_logical_replication_slot(slot, 'test_decoding');\n-- 그 이후 원본 변경·커밋\nSELECT lsn, data FROM pg_logical_slot_peek_changes(slot, NULL, NULL);",
        "실제 논리 복제 슬롯을 만들고 원본 트랜잭션을 실행한다. peek는 읽기만 하므로 진행 위치는 아직 확인하지 않는다. 현재 원본과 WAL 출력을 함께 기록한다.",
        "원본 최종 1행 / 대상 0행 / 커밋된 변경 4개 / 롤백 ID는 변경 스트림에 없음.",
        "CDC는 현재 테이블을 SELECT한 결과가 아니다. 생성 뒤 삭제된 행도 로그에는 INSERT·DELETE로 나타나고, 롤백된 작업은 이 커밋 스트림에 나타나지 않는다.",
        "test_decoding은 학습용 출력 플러그인이다. Debezium 배포나 범용 파서를 구현한 것은 아니다. CDC 행 변경만으로 ‘사용자가 배송 완료를 승인했다’ 같은 업무 의도를 모두 알 수는 없다.")
    apply=make("cdc_apply","문제 · 반영은 끝났는데 읽은 위치를 못 남겼다","08 · CDC — 복구 간극",
        "앞의 WAL 변경을 대상에 반영한 뒤 슬롯 진행 위치 확인을 생략한다. 소비자가 그 사이 멈춘 실패 지점을 만든다.",
        "LSN은 WAL 위치다. 소비자는 어디까지 안전하게 처리했는지 기록해야 재개할 때 빠뜨리거나 중복 처리하는 위험을 다룰 수 있다.",
        "책 내용을 노트에 옮겼지만 책갈피를 옮기기 전에 자리를 떠난 상황이다. 다음에는 같은 부분부터 다시 읽을 수 있다.",
        "apply_to_target(change)\n# 여기서 중단\nacknowledge_source_position(lsn)",
        "WITH seen AS (\n  INSERT INTO cdc_seen(event_key) VALUES (?)\n  ON CONFLICT DO NOTHING RETURNING event_key\n), applied AS (\n  -- seen이 새로 기록된 경우만 대상 변경; 한 SQL 트랜잭션\n) SELECT count(*) FROM seen;",
        "대상 반영과 이벤트 중복 기록을 같은 트랜잭션으로 묶는다. 적용 후 confirmed_flush_lsn은 일부러 진행시키지 않고 종료한다. 프로세스를 강제 종료한 실험은 아니다.",
        "신규 적용 이벤트 4 / 원본·대상 각각 1행 / 위치 전=후. 현재 대상 상태가 맞아도 다음 전달이 중복될 수 있다.",
        "원본의 진행 위치와 대상 DB 커밋은 자동으로 하나의 트랜잭션이 되지 않는다. 먼저 진행 위치를 넘기면 미반영 데이터를 놓칠 수 있다.",
        "실습은 작고 고정된 원본 변경 전체를 순서대로 처리한다. 대규모 스트림의 트랜잭션 경계·초기 스냅샷·DDL·삭제 키·순서·파티션은 추가 설계가 필요하다.","cdc_lag")
    resume=make("cdc_resume","해결 · 같은 변경을 다시 읽어도 안전하게 재개","08 · CDC — 재전달",
        "새 디코딩 호출로 슬롯에서 다시 읽는다. 앞의 변경을 재수신하지만 이미 적용한 이벤트는 건너뛴다.",
        "at-least-once 전달에서는 같은 변경을 다시 받을 수 있다. 처리 효과와 중복 기록을 원자적으로 저장하고 처리 완료 뒤 원본 위치를 확인한다.",
        "책갈피가 옛 위치여도 이미 옮긴 문장의 번호를 확인하면 노트를 두 번 쓰지 않아도 된다.",
        "apply(change)\n# 위치 확인 전 멈춤 → 같은 change 재수신",
        "peek_changes(slot)\napply_if_unseen(change)\npg_replication_slot_advance(slot, last_commit_lsn)\n# 실습 완료 시 이번 슬롯만 drop",
        "같은 이벤트를 건너뛴 실제 건수를 센 뒤 읽은 마지막 COMMIT까지만 슬롯 위치를 넘긴다. 증거를 저장하고 이번 슬롯을 닫아 불필요한 WAL 보관을 끝낸다.",
        "원본 변경 재수신 4 / 신규 적용 0 / 중복 건너뛰기 4 / 원본·대상 일치 / 슬롯 정리 후 0.",
        "중복 방지와 위치 확인의 순서가 복구를 가능하게 한다. 대상 현재 행 수만 봐서는 재전달을 알아채기 어려우므로 이벤트 수와 위치를 같이 본다.",
        "운영 CDC는 슬롯을 계속 유지한다. 실습 슬롯은 종료하며, 중간 방치 시 WAL 보관이 생긴다. max_slot_wal_keep_size=128MB는 정확한 디스크 사용 상한이 아니라 체크포인트 시 슬롯 무효화 기준이다.","cdc_apply")
    single=make("failover_single","이중화 문제 · 주 제공자가 거절하면 업무도 멈춘다","09 · 이중화 — 단일 의존",
        "포인트 주 제공자 B가 지급 전 확정 거절한다. 별도 프로세스 B2는 정상이지만 단일 경로만 호출한다. 이 예제는 리뷰 저장 없이 지급 경로에 집중한다.",
        "연동 서비스 이중화는 같은 업무를 처리할 대체 제공자를 준비해 한 제공자의 장애 때 다른 경로를 사용할 수 있게 하는 것이다.",
        "문자 업체가 한 곳뿐이면 그 업체 장애 때 인증 문자를 못 보낸다. 다른 업체가 있어도 전환 코드가 없으면 도움이 되지 않는다.",
        "primary.grant(id); // 다른 경로 없음",
        "// 다음 단계: 미처리 확정 여부를 확인한 뒤 backup.grant(id)",
        "주 제공자에 지급 전 503 장애를 주입하고 mode=single로 호출한다. 응답 outcome과 두 실제 장부를 조회한다.",
        "outcome REJECTED / 주 지급 0 / 대체 지급 0.",
        "대체 서비스가 존재하는 것과 실제로 그곳으로 전환하는 것은 다른 문제다.",
        "B2는 별도 컨테이너·별도 장부지만 같은 노트북과 DB를 공유한다. 독립 리전·독립 DB 장애 대응 구성은 아니다.")
    switch=make("failover_switch","해결 · 미처리 확정 때 대체 제공자로 전환","09 · 이중화 — 안전한 전환",
        "같은 주 제공자 지급 전 거절 상황에서 이번에는 미처리 계약을 확인하고 정상 B2로 보낸다.",
        "페일오버는 주 경로 실패 때 대체 경로로 전환하는 것이다. 부작용 있는 업무에서는 먼저 이전 시도의 결과를 구분해야 한다.",
        "첫 업체가 ‘접수하지 않았다’고 확정한 주문을 다른 업체에 맡기는 경우다.",
        "primary.grant(id);",
        "try { primary.grant(id); }\ncatch (error) {\n  if (contractConfirmsNotApplied(error)) backup.grant(id);\n  else return UNKNOWN;\n}",
        "mode=safe는 503과 이 실습 전용 X-Lab-Not-Applied:true 계약을 함께 검사한다. 일반 503만 보고 전환하지 않는다. 실제 B2 HTTP 요청·별도 장부로 성공을 확인한다.",
        "outcome CONFIRMED / provider backup / 주 지급 0 / 대체 지급 1 / 합계 100.",
        "이미 고장 난 서비스를 차단하는 서킷과 달리, 이 단계는 업무를 수행할 대체 경로를 제공한다.",
        "백업도 실패할 수 있다. 용량·전환 비용·기능 차이·관측·복귀 정책이 필요하다. 이 구현은 교육용 계약이며 범용 장애 전환 정책이 아니다.","failover_single")
    unknown=make("failover_unknown","주의 · 타임아웃이면 다른 곳에 바로 보내도 될까?","09 · 이중화 — 중복 위험",
        "주 B가 먼저 지급하고 응답만 3초 지연한다. 새 ID 두 개로 위험한 무조건 전환과 결과 불명 보류를 비교한다.",
        "UNKNOWN은 실패 확정이 아니라 결과를 모른다는 상태다. 제공자별 멱등 키는 서로 다른 제공자의 장부까지 중복 방지하지 않는다.",
        "첫 배달 업체가 답이 없다고 두 번째 업체에도 주문하면 양쪽에서 음식이 올 수 있다.",
        "catch (timeout) { backup.grant(id); } // 위험한 비교 분기",
        "catch (timeout) { return UNKNOWN; }\n// 결과 조회·대사 전에는 다른 제공자에 지급하지 않는다.",
        "첫 ID는 mode=unsafe, 두 번째는 mode=safe로 호출한다. 각 요청의 B 후속 지급 완료를 기다린 뒤 두 장부를 조회한다. 의도적인 중복은 별도 실험 데이터에만 발생한다.",
        "unsafe: 주 1+대체 1=200. safe: UNKNOWN이지만 주 1+대체 0=100. 빠른 성공 응답만으로 안전성을 판단하지 않는다.",
        "B와 B2는 각각 같은 키의 중복을 막아도 두 장부를 공유하지 않는다. 같은 키를 전달하는 것만으로 제공자 간 exactly-once가 되지 않는다.",
        "unsafe 분기는 잘못된 설계를 재현하기 위한 것이다. 실제 결제·지급에 적용하면 안 된다. 실험 후 기존 중복을 자동 취소하지 않는다.","failover_switch")
    reconcile=make("failover_reconcile","복구 · 새로 지급하지 말고 기존 결과 확인","09 · 이중화 — 결과 대사",
        "앞의 safe ID에 대해 새 지급 요청을 보내지 않고 주 제공자의 실제 지급 장부를 조회한다.",
        "대사는 두 시스템 기록을 비교해 불명·누락·중복 상태를 확인하는 과정이다. 확인 이후 보정 여부는 업무 정책으로 결정한다.",
        "답이 없던 업체의 주문 내역을 확인한 뒤 이미 접수됐다면 재주문하지 않는다.",
        "UNKNOWN → 바로 실패로 처리하거나 새 제공자에 재지급",
        "result = primary.lookup(businessId)\nif result.isApplied():\n    confirm_existing_result() // 새 지급 없음",
        "B 지연을 정상화하고 해당 업무 ID를 /grants에서 찾아 두 장부의 실제 값을 기록한다. 실습은 상태 조회만 하며 사용자 업무 상태 머신이나 자동 취소는 구현하지 않는다.",
        "앞 safe ID의 주 지급 1 / 대체 지급 0 / 합계 100이 유지된다. 추가 지급 없이 기존 성공을 확인한다.",
        "불명 상태를 보류하고 조회 가능한 업무 키를 남겨야 나중에 정확히 확인할 수 있다.",
        "조회도 실패하거나 최종 상태 반영이 늦을 수 있다. 운영에서는 대사 주기·종료 조건·보상·수동 확인 경로가 필요하다.","failover_unknown")
    for s in (single,switch,unknown,reconcile): s["codeSource"]="FailoverController.java / PointsController.java / scripts/extension_actions.py"
    steps[-1]["does"]+=" 이번 세션의 미완료 CDC 슬롯도 종료하고 대체 제공자의 장애 설정을 정상화한다. 배치 파일과 DB 행은 보존한다."
    return steps[:-1]+[batch_wait,partial,batch,lag,apply,resume,single,switch,unknown,reconcile]+steps[-1:]
